### ISSUE TITLE
Test 3 Issue

### ISSUE THREAD

**Issue by cawhite08** [msu-csc232-sp24/lab01#5]
I may be doing something wrong, but I have pored over the code I wrote as well as the test code. The test code (for test 3) is looking for a return value of 1 when calling the indexOfMaxGrade function. If the function runs as it should, the return value, based on the provided array in test, should be 8. Index 8 points to the double "100.00" which is the highest grade in the array that is provided. Like I said, maybe I am doing something wrong, but I am almost certain my code is correct. Thanks!
<img width="695" alt="test 3 error ss" src="https://github.com/msu-csc232-sp24/lab01/assets/133604588/072e134a-cb83-424b-816a-0d8c595d250f">

**Comment by cawhite08** [comment]
I just realized I was literally covering the 100.00 at index 8 due to my mouse placement. It is there, I promise LOL

**Comment by professordaehn** [comment]
You're misunderstanding the intent of the test. `maxGrade()` should give you the index of course, i.e., of the row, that contains the maximum grade. Since the maximum grade of 100 is in the second row, i.e., the row indexed by the number 1, the expected value is, in fact, 1. You're looking at this as if it were a one dimensional array...

**Comment by cawhite08** [comment]
Ah I see. I was calculating it using pointer arithmetic when I originally made the function (I was passing by reference), and forgot to change my calculation whenever I switched parameters. Thank you for the info.

**Comment by professordaehn** [comment]
Thanks for raising the issue, and I'm glad we got that cleared up.
